### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by wazowski78** [senior-sigan/Wazzup#2]
Hi,
I would like to know if this method is still working. Thank you very much for your work :)

Regards.

**Comment by senior-sigan** [comment]
@wazowski78 Hello.
I've not tested it on the latest whats app version. But I suppose it still works because usually, this kind of attack doesn't count as possible. There are some ways to mitigate it: to check last login ip/location. Even asking code from the SMS doesn't help here. Because this attack is a "mirror". Ah, yes, the captcha should help, but I didn't think how to "copy" captcha.

**Comment by wazowski78** [comment]
Thanks a lot for your answer, can you give me some install instructions in order to test it please?
